version: "3.7"

services:
    # redis:
    #     image: redis
    #     container_name: redis_container
    #     environment:
    #         - ALLOW_EMPTY_PASSWORDS=yes
    #     ports:
    #         - "6379:6379"

    # redis-commander:
    #     container_name: redis-commander_container
    #     image: rediscommander/redis-commander
    #     restart: always
    #     environment:
    #         - REDIS_HOSTS=local:redis:6379
    #     ports:
    #         - "8081:8081"

    server:
        container_name: backend_container
        image: node
        build: .
        command: npm run start:dev
        environment:
            REDIS_URL: redis:6379
            CHOKINDAR_USEPOLLING: "true"
            CHOCKINDAR_INTERVAL: 1000
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        networks:
            default:
                aliases:
                    - back-end
        # depends_on:
        #     - redis
