version: "3.7"

services:
  redis:
    image: redis:6.2-alpine
    command: redis-server
    container_name: redis_container
    environment:
      - ALLOW_EMPTY_PASSWORDS=yes
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander_container
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  server:
    container_name: backend_container
    build: .
    image: node:16-alpine
    environment:
      REDIS_URL: redis://redis:6379
      AC_BASE_URL: https://curtisstreetmedia1651721711.api-us1.com/api/3/
      API_TOKEN: f19bf8f2f30f613b97e2c0bdc222cac620a9ef4969fd21c79b64a528ce58fa2fd7aa1de9
      SEARCH_FIELD: contact
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - redis
