const {
  ac_axios,
  dire_axios,
  ac_axios_dev,
  ac_listAllCustomFieldsContacts,
  ac_listAllCustomFieldsDeals,
  ac_listAllContacts,
  ac_listAllUsers,
  dire_listAllContacts,
  dire_listAllCustomFieldsDeals,
  dire_listAllDeals,
  dire_listAllPipelines,
  dire_listAllCustomFieldsContacts,
  dire_listAllTaskTypes,
  dire_listAllTasks,
  dire_listAllUsers,
  ac_listAllDeals,
  ac_listAllTasks,
  ac_listAllTaskTypes,
  ac_listAllPipelines,
  ac_listAllStages,
  getData,
} = require("./axios");

module.exports = {
  ac_axios,
  dire_axios,
  ac_axios_dev,
  ac_listAllCustomFieldsContacts,
  ac_listAllCustomFieldsDeals,
  ac_listAllContacts,
  ac_listAllUsers,
  dire_listAllContacts,
  dire_listAllUsers,
  dire_listAllCustomFieldsDeals,
  dire_listAllDeals,
  dire_listAllPipelines,
  dire_listAllCustomFieldsContacts,
  dire_listAllTaskTypes,
  dire_listAllTasks,
  ac_listAllDeals,
  ac_listAllTasks,
  ac_listAllTaskTypes,
  ac_listAllPipelines,
  ac_listAllStages,
  getData,
};
